Update action.yaml

diff --git a/melange-build/action.yaml b/melange-build/action.yaml
--- a/melange-build/action.yaml
+++ b/melange-build/action.yaml
@@ -154,7 +154,11 @@ runs:
       if: ${{ inputs.sign-package == 'true' }}
       shell: bash
       run: |
-        : "${{ inputs.signing-key:?Error: sign-package is enabled but signing-key input is not set}"
+        if [[ -z "${{ inputs.signing-key }}" ]]; then
+          echo "Error: sign-package is enabled but signing-key input is not set."
+          exit 1
+        fi
+        
         KEY_PATH="${RUNNER_TEMP}/.melange/melange-signing.rsa"
         mkdir -p "$(dirname "$KEY_PATH")"
         chmod 700 "$(dirname "$KEY_PATH")"
